version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/todos
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: