apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-app
  labels:
    app: flask-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-todo-app
  template:
    metadata:
      labels:
        app: flask-todo-app
    spec:
      containers:
      - name: flask-todo-app
        image: vigneshvicky97/basic_to_do_app:latest
        ports:
        - containerPort: 5000
